services:
    mongo:
        image: mongo:latest
        container_name: trakn_app_mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
            - ./devops/mongodb-init:/docker-entrypoint-initdb.d
volumes:
    mongo-data:
